/* eslint-disable */
/**
 * Stub generated by clonk-x-factory template.
 * Real file is generated by `npx convex deploy` — do not edit.
 */
export const api: any = new Proxy(
  {},
  {
    get: (_target, tableName) =>
      new Proxy(
        {},
        {
          get: (_t, fnName) => `${String(tableName)}:${String(fnName)}`,
        },
      ),
  },
);
export const internal: any = api;
