/* eslint-disable */
/**
 * Stub generated by clonk-x-factory template.
 * Real file is generated by `npx convex deploy` — do not edit.
 */
export type Id<TableName extends string = any> = string & {
  __tableName: TableName;
};
export type Doc<TableName extends string = any> = any;
export type DataModel = any;
export type TableNames = string;
