/* eslint-disable */
/**
 * Stub generated by clonk-x-factory template.
 * Real file is generated by `npx convex deploy` — do not edit.
 *
 * Provides untyped function constructors so tsc passes before codegen.
 */
type AnyFn = (args: any) => any;

export const query: AnyFn = (fn: any) => fn;
export const mutation: AnyFn = (fn: any) => fn;
export const action: AnyFn = (fn: any) => fn;
export const internalQuery: AnyFn = (fn: any) => fn;
export const internalMutation: AnyFn = (fn: any) => fn;
export const internalAction: AnyFn = (fn: any) => fn;
